name: Swift

on:
  push:
    branches: [ "master/AltStore" ]
  pull_request:
    branches: [ "master/AltStore" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
